export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const GET_CAUSE_AS_VOLUNTEER_OR_ADMIN = 'GET_CAUSE_AS_VOLUNTEER_OR_ADMIN';
export const GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_FAIL = 'GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_FAIL';

export const SET_DETAILS = "SET_DETAILS ";
export const GET_CAUSE_DETAILS = "GET_CAUSE_DETAILS ";
export const GET_CAUSE_DETAILS_FAIL = "GET_CAUSE_DETAILS_FAIL ";

export const REVIEW_A_SINGLE_CAUSE_START = 'REVIEW_A_SINGLE_CAUSE_START';
export const REVIEW_A_SINGLE_CAUSE_SUCCESS = 'REVIEW_A_SINGLE_CAUSE_SUCCESS';
export const REVIEW_A_SINGLE_CAUSE_FAIL = 'REVIEW_A_SINGLE_CAUSE_FAIL';

export const GET_VOLUNTEERS_FOR_APPROVAL_START = 'GET_VOLUNTEER_FOR_APPROVAL_START';
export const GET_VOLUNTEERS_FOR_APPROVAL_SUCCESS = 'GET_VOLUNTEER_FOR_APPROVAL_SUCCESS';
export const GET_VOLUNTEERS_FOR_APPROVAL_FAIL = 'GET_VOLUNTEER_FOR_APPROVAL_FAIL';

export const GET_VOLUNTEER_DETAILS_FOR_APPROVAL_START = 'GET_VOLUNTEER_FOR_APPROVAL_START';
export const GET_VOLUNTEER_DETAILS_FOR_APPROVAL_SUCCESS = 'GET_VOLUNTEER_FOR_APPROVAL_SUCCESS';
export const GET_VOLUNTEER_DETAILS_FOR_APPROVAL_FAIL = 'GET_VOLUNTEER_FOR_APPROVAL_FAIL';

export const ACCEPT_OR_REJECT_A_VOLUNTEER_START = 'ACCEPT_OR_REJECT_A_VOLUNTEER_START';
export const ACCEPT_OR_REJECT_A_VOLUNTEER_SUCCESS = 'ACCEPT_OR_REJECT_A_VOLUNTEER_SUCCESS';
export const ACCEPT_OR_REJECT_A_VOLUNTEER_FAIL = 'ACCEPT_OR_REJECT_A_VOLUNTEER_FAIL';

export const GATHER_PERSONAL_DETAILS = 'GATHER_PERSONAL_DETAILS';
export const ACCOUNT_DETAILS = 'ACCOUNT_DETAILS';
export const REG_START = 'REG_START';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FAIL = 'REG_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_USER = 'GET_USER';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const Find_User = 'Find_User';