export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const USER_PROFILE_START = 'USER_PROFILE_START';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const GET_MY_CAUSES_START = 'GET_MY_CAUSES_START';
export const GET_MY_CAUSES_SUCCESS = 'GET_MY_CAUSES_SUCCESS';
export const GET_MY_CAUSES_FAIL = 'GET_MY_CAUSES_FAIL';

export const GET_MY_CAUSE_DETAILS_START = 'GET_MY_CAUSE_DETAILS_START';
export const GET_MY_CAUSE_DETAILS_SUCCESS = 'GET_MY_CAUSE_DETAILS_SUCCESS';
export const GET_MY_CAUSE_DETAILS_FAIL = 'GET_MY_CAUSE_DETAILS_FAIL';

export const DELETE_MY_CAUSE_START = 'DELETE_MY_CAUSE_START';
export const DELETE_MY_CAUSE_SUCCESS = 'DELETE_MY_CAUSE_SUCCESS';
export const DELETE_MY_CAUSE_FAIL = 'DELETE_MY_CAUSE_FAIL';

export const EDIT_MY_CAUSE_START = 'EDIT_MY_CAUSE_START';
export const EDIT_MY_CAUSE_SUCCESS = 'EDIT_MY_CAUSE_SUCCESS';
export const EDIT_MY_CAUSE_FAIL = 'EDIT_MY_CAUSE_FAIL';

export const GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_START = 'GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_START';
export const GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_SUCCESS = 'GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_SUCCESS';
export const GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_FAIL = 'GET_CAUSE_AS_VOLUNTEER_OR_ADMIN_FAIL';

export const SET_DETAILS = "SET_DETAILS ";
export const GET_CAUSE_DETAILS = "GET_CAUSE_DETAILS ";
export const GET_CAUSE_DETAILS_FAIL = "GET_CAUSE_DETAILS_FAIL ";

export const REVIEW_A_SINGLE_CAUSE_START = 'REVIEW_A_SINGLE_CAUSE_START';
export const REVIEW_A_SINGLE_CAUSE_SUCCESS = 'REVIEW_A_SINGLE_CAUSE_SUCCESS';
export const REVIEW_A_SINGLE_CAUSE_FAIL = 'REVIEW_A_SINGLE_CAUSE_FAIL';

export const GET_CAUSES_FOR_APPROVAL_START = 'GET_CAUSES_FOR_APPROVAL_START';
export const GET_CAUSES_FOR_APPROVAL_SUCCESS = 'GET_CAUSES_FOR_APPROVAL_SUCCESS';
export const GET_CAUSES_FOR_APPROVAL_FAIL = 'GET_CAUSES_FOR_APPROVAL_FAIL';

export const ACCEPT_OR_REJECT_CAUSE_START = 'ACCEPT_OR_REJECT_CAUSE_START';
export const ACCEPT_OR_REJECT_CAUSE_SUCCESS = 'ACCEPT_OR_REJECT_CAUSE_SUCCESS';
export const ACCEPT_OR_REJECT_CAUSE_FAIL = 'ACCEPT_OR_REJECT_CAUSE_FAIL';

export const GET_VOLUNTEERS_FOR_APPROVAL_START = 'GET_VOLUNTEERS_FOR_APPROVAL_START';
export const GET_VOLUNTEERS_FOR_APPROVAL_SUCCESS = 'GET_VOLUNTEERS_FOR_APPROVAL_SUCCESS';
export const GET_VOLUNTEERS_FOR_APPROVAL_FAIL = 'GET_VOLUNTEERS_FOR_APPROVAL_FAIL';

export const GET_VOLUNTEER_DETAILS_FOR_APPROVAL_START = 'GET_VOLUNTEER_FOR_APPROVAL_START';
export const GET_VOLUNTEER_DETAILS_FOR_APPROVAL_SUCCESS = 'GET_VOLUNTEER_FOR_APPROVAL_SUCCESS';
export const GET_VOLUNTEER_DETAILS_FOR_APPROVAL_FAIL = 'GET_VOLUNTEER_FOR_APPROVAL_FAIL';

export const ACCEPT_OR_REJECT_A_VOLUNTEER_START = 'ACCEPT_OR_REJECT_A_VOLUNTEER_START';
export const ACCEPT_OR_REJECT_A_VOLUNTEER_SUCCESS = 'ACCEPT_OR_REJECT_A_VOLUNTEER_SUCCESS';
export const ACCEPT_OR_REJECT_A_VOLUNTEER_FAIL = 'ACCEPT_OR_REJECT_A_VOLUNTEER_FAIL';

export const GET_CAUSES_FOR_RESOLUTION_START = 'GET_CAUSES_FOR_RESOLUTION_START';
export const GET_CAUSES_FOR_RESOLUTION_SUCCESS = 'GET_CAUSES_FOR_RESOLUTION_SUCCESS';
export const GET_CAUSES_FOR_RESOLUTION_FAIL = 'GET_CAUSES_FOR_RESOLUTION_FAIL';

export const RESOLVE_CAUSE_START = 'RESOLVE_CAUSE_START';
export const RESOLVE_CAUSE_SUCCESS = 'RESOLVE_CAUSE_SUCCESS';
export const RESOLVE_CAUSE_FAIL = 'RESOLVE_CAUSE_FAIL';

export const CREATE_MY_SUCCESS_STORY_START = 'CREATE_MY_SUCCESS_STORY_START';
export const CREATE_MY_SUCCESS_STORY_SUCCESS = 'CREATE_MY_SUCCESS_STORY_SUCCESS';
export const CREATE_MY_SUCCESS_STORY_FAIL = 'CREATE_MY_SUCCESS_STORY_FAIL';

export const GET_MY_SUCCESS_STORIES_START = 'GET_MY_SUCCESS_STORIES_START';
export const GET_MY_SUCCESS_STORIES_SUCCESS = 'GET_MY_SUCCESS_STORIES_SUCCESS';
export const GET_MY_SUCCESS_STORIES_FAIL = 'GET_MY_SUCCESS_STORIES_FAIL';

export const CHECK_SUCCESS_STORY_DETAILS_START = 'CHECK_SUCCESS_STORY_DETAILS_START';
export const CHECK_SUCCESS_STORY_DETAILS_SUCCESS = 'CHECK_SUCCESS_STORY_DETAILS_SUCCESS';
export const CHECK_SUCCESS_STORY_DETAILS_FAIL = 'CHECK_SUCCESS_STORY_DETAILS_FAIL';

export const EDIT_MY_SUCCESS_STORY_START = 'EDIT_MY_SUCCESS_STORY_START';
export const EDIT_MY_SUCCESS_STORY_SUCCESS = 'EDIT_MY_SUCCESS_STORY_SUCCESS';
export const EDIT_MY_SUCCESS_STORY_FAIL = 'EDIT_MY_SUCCESS_STORY_FAIL';

export const DELETE_MY_SUCCESS_STORY_START = 'DELETE_MY_SUCCESS_STORY_START';
export const DELETE_MY_SUCCESS_STORY_SUCCESS = 'DELETE_MY_SUCCESS_STORY_SUCCESS';
export const DELETE_MY_SUCCESS_STORY_FAIL = 'DELETE_MY_SUCCESS_STORY_FAIL';

export const GET_ALL_SUCCESS_STORIES_START = 'GET_ALL_SUCCESS_STORIES_START';
export const GET_ALL_SUCCESS_STORIES_SUCCESS = 'GET_ALL_SUCCESS_STORIES_SUCCESS';
export const GET_ALL_SUCCESS_STORIES_FAIL = 'GET_ALL_SUCCESS_STORIES_FAIL';

export const CREATE_AN_EVENT_START = 'CREATE_AN_EVENT_START';
export const CREATE_AN_EVENT_SUCCESS = 'CREATE_AN_EVENT_SUCCESS';
export const CREATE_AN_EVENT_FAIL = 'CREATE_AN_EVENT_FAIL';

export const GET_ALL_MY_EVENTS_START = 'GET_ALL_MY_EVENTS_START';
export const GET_ALL_MY_EVENTS_SUCCESS = 'GET_ALL_MY_EVENTS_SUCCESS';
export const GET_ALL_MY_EVENTS_FAIL = 'GET_ALL_MY_EVENTS_FAIL';

export const CHECK_EVENT_DETAILS_START = 'CHECK_EVENT_DETAILS_START';
export const CHECK_EVENT_DETAILS_SUCCESS = 'CHECK_EVENT_DETAILS_SUCCESS';
export const CHECK_EVENT_DETAILS_FAIL = 'CHECK_EVENT_DETAILS_FAIL';

export const EDIT_EVENT_START = 'EDIT_EVENT_START';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAIL = 'EDIT_EVENT_FAIL';

export const DELETE_MY_EVENT_START = 'DELETE_MY_EVENT_START';
export const DELETE_MY_EVENT_SUCCESS = 'DELETE_MY_EVENT_SUCCESS';
export const DELETE_MY_EVENT_FAIL = 'DELETE_MY_EVENT_FAIL';

export const GET_ALL_EVENTS_START = 'GET_ALL_EVENTS_START';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const GET_ALL_EVENTS_FAIL = 'GET_ALL_EVENTS_FAIL';

export const GET_ALL_EVENTS_BY_CLEADER_START = 'GET_ALL_EVENTS_BY_CLEADER_START';
export const GET_ALL_EVENTS_BY_CLEADER_SUCCESS = 'GET_ALL_EVENTS_BY_CLEADER_SUCCESS';
export const GET_ALL_EVENTS_BY_CLEADER_FAIL = 'GET_ALL_EVENTS_BY_CLEADER_FAIL';

export const MAKE_DECISION_ON_EVENT_START = 'MAKE_DECISION_ON_EVENT_START';
export const MAKE_DECISION_ON_EVENT_SUCCESS = 'MAKE_DECISION_ON_EVENT_SUCCESS';
export const MAKE_DECISION_ON_EVENT_FAIL = 'MAKE_DECISION_ON_EVENT_FAIL';

export const GET_ALL_EVENTS_TO_BE_RESOLVED_START = 'GET_ALL_EVENTS_TO_BE_RESOLVED_START';
export const GET_ALL_EVENTS_TO_BE_RESOLVED_SUCCESS = 'GET_ALL_EVENTS_TO_BE_RESOLVED_SUCCESS';
export const GET_ALL_EVENTS_TO_BE_RESOLVED_FAIL = 'GET_ALL_EVENTS_TO_BE_RESOLVED_FAIL';

export const RESOLVE_EVENT_START = 'RESOLVE_EVENT_START';
export const RESOLVE_EVENT_SUCCESS = 'RESOLVE_EVENT_SUCCESS';
export const RESOLVE_EVENT_FAIL = 'RESOLVE_EVENT_FAIL';

export const GATHER_PERSONAL_DETAILS = 'GATHER_PERSONAL_DETAILS';
export const ACCOUNT_DETAILS = 'ACCOUNT_DETAILS';
export const REG_START = 'REG_START';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FAIL = 'REG_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_USER = 'GET_USER';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const Find_User = 'Find_User';